variants:
    generic:
        production:
        
            uses:
                swfw_shared_xx: &sdsdsxs
                    release: "1.3"
                    variant: generic
                adaptive_cfg: &adaptive_cfg
                    release: "1.2"
                    variant: generic